// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_eDLOhTJPvoAn2IMuk29_h-NXLtMLWQM',
    appId: '1:287375133768:web:21e85544a9d4d6f1a11c7d',
    messagingSenderId: '287375133768',
    projectId: 'awesome-99947',
    authDomain: 'awesome-99947.firebaseapp.com',
    storageBucket: 'awesome-99947.appspot.com',
    measurementId: 'G-DL1LFRB8J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSUO0y3eksgSyqSRwq5SzTiyj8YlnOew',
    appId: '1:287375133768:android:84ad8a8188b35adaa11c7d',
    messagingSenderId: '287375133768',
    projectId: 'awesome-99947',
    storageBucket: 'awesome-99947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDudmcQuk_Q00TxtfIznzzJcmyY2j5jk8c',
    appId: '1:287375133768:ios:4de852612db0c9d1a11c7d',
    messagingSenderId: '287375133768',
    projectId: 'awesome-99947',
    storageBucket: 'awesome-99947.appspot.com',
    iosClientId: '287375133768-ebm94uatfpcmrnrupt0u54o2244o3u5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDudmcQuk_Q00TxtfIznzzJcmyY2j5jk8c',
    appId: '1:287375133768:ios:4de852612db0c9d1a11c7d',
    messagingSenderId: '287375133768',
    projectId: 'awesome-99947',
    storageBucket: 'awesome-99947.appspot.com',
    iosClientId: '287375133768-ebm94uatfpcmrnrupt0u54o2244o3u5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
